In [2]:
import torch
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
# tensor는 pytorch의 기본 단위이며, GPU 연산을 가능케 한다.
x = torch.empty(5, 4)
print(x)
torch.ones(3, 3)
torch.zeros(2, 3)
torch.rand(5, 6)

tensor([[-1.4861e+28,  7.3989e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[0.2782, 0.7974, 0.8497, 0.6285, 0.8121, 0.7207],
        [0.7176, 0.7843, 0.0579, 0.6424, 0.5463, 0.3732],
        [0.6652, 0.7751, 0.8953, 0.3369, 0.2201, 0.1348],
        [0.1962, 0.9273, 0.1885, 0.4233, 0.6678, 0.5346],
        [0.0715, 0.8422, 0.2173, 0.6833, 0.4905, 0.6134]])

In [4]:
# list, numpy 배열을 텐서로 만들 수 있다.
l = [13, 4]
r = np.array([4, 56, 7])
torch.tensor(l)
torch.FloatTensor(r)

tensor([13,  4])

tensor([ 4., 56.,  7.])

In [ ]:
# 텐서의 크기, 타입, 연산
x.size()[0]
x.size()[1]
type(x)

x = torch.rand(2, 2)
y = torch.rand(2, 2)
x + y
torch.add(x, y)
y.add_(x)

5

4

torch.Tensor

tensor([[0.5606, 0.9976],
        [0.7939, 0.2839]])

tensor([[0.5606, 0.9976],
        [0.7939, 0.2839]])

tensor([[0.5606, 0.9976],
        [0.7939, 0.2839]])

In [ ]:
# 텐서의 크기 변환
x = torch.rand(8, 8)
x.size()

x.view(64)


torch.Size([8, 8])