In [1]:
import torch
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# tensor는 pytorch의 기본 단위이며, GPU 연산을 가능케 한다.
x = torch.empty(5, 4)
print(x)
torch.ones(3, 3)
torch.zeros(2, 3)
torch.rand(5, 6)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[0.1412, 0.3325, 0.9215, 0.0480, 0.5803, 0.4394],
        [0.2324, 0.0057, 0.3376, 0.5291, 0.5825, 0.6442],
        [0.2877, 0.3489, 0.6413, 0.8730, 0.9766, 0.6153],
        [0.2439, 0.0842, 0.0257, 0.2035, 0.3498, 0.3159],
        [0.4577, 0.7316, 0.6191, 0.3684, 0.7152, 0.0579]])

In [3]:
# list, numpy 배열을 텐서로 만들 수 있다.
l = [13, 4]
r = np.array([4, 56, 7])
torch.tensor(l)

# 구체적인 텐서 타입 정의 가능
torch.FloatTensor(r)
torch.LongTensor(l)

tensor([13,  4])

tensor([ 4., 56.,  7.])

tensor([13,  4])

In [4]:
# 텐서의 크기, 타입, 연산
x.size()[0]
x.size()[1]
x.size(1)
type(x)

x = torch.rand(2, 2)
y = torch.rand(2, 2)

x + y
torch.add(x, y)
y.add_(x)

5

4

4

torch.Tensor

tensor([[1.5662, 0.4876],
        [1.4279, 1.7184]])

tensor([[1.5662, 0.4876],
        [1.4279, 1.7184]])

tensor([[1.5662, 0.4876],
        [1.4279, 1.7184]])

In [5]:
# 텐서의 크기 변환
x = torch.rand(8, 8)
x.size()

x.view(64).size()
x.view(-1, 4, 4).size()

torch.Size([8, 8])

torch.Size([64])

torch.Size([4, 4, 4])

In [6]:
# 텐서에서 넘파이 배열로 변환
x = torch.rand(8, 8)
x
y = x.numpy()
type(y)
y

tensor([[0.4335, 0.2842, 0.8258, 0.1735, 0.7965, 0.1039, 0.2069, 0.0958],
        [0.9915, 0.8484, 0.1079, 0.8174, 0.0518, 0.6319, 0.7811, 0.1786],
        [0.2484, 0.6419, 0.1837, 0.1604, 0.2068, 0.1233, 0.1769, 0.7503],
        [0.8692, 0.8717, 0.4205, 0.3179, 0.3430, 0.7882, 0.6697, 0.8110],
        [0.2347, 0.0442, 0.9406, 0.9246, 0.9610, 0.3252, 0.7491, 0.6673],
        [0.9610, 0.9149, 0.2363, 0.8586, 0.6685, 0.7924, 0.5117, 0.5085],
        [0.0411, 0.0348, 0.4892, 0.8489, 0.6030, 0.2595, 0.6872, 0.2041],
        [0.6044, 0.5013, 0.7505, 0.9672, 0.1460, 0.5632, 0.6344, 0.4955]])

numpy.ndarray

array([[0.43350774, 0.2841658 , 0.825761  , 0.17348915, 0.7964874 ,
        0.10388207, 0.20694906, 0.09578812],
       [0.9914606 , 0.84841275, 0.10788041, 0.8174064 , 0.05178303,
        0.63194096, 0.7810859 , 0.17864436],
       [0.24844384, 0.6419355 , 0.18371534, 0.1603592 , 0.20681906,
        0.12328637, 0.17690992, 0.7503293 ],
       [0.8692238 , 0.87165105, 0.42048073, 0.3179356 , 0.34300137,
        0.7882364 , 0.66965944, 0.8110309 ],
       [0.2347449 , 0.04418343, 0.94055164, 0.92463636, 0.96101063,
        0.3252439 , 0.7490751 , 0.6672712 ],
       [0.9610376 , 0.9149217 , 0.23631144, 0.85862094, 0.6685312 ,
        0.79240125, 0.5116703 , 0.5085176 ],
       [0.04107189, 0.03476775, 0.4891562 , 0.84890586, 0.6029908 ,
        0.2595278 , 0.6872187 , 0.20407963],
       [0.6044436 , 0.5013479 , 0.75046283, 0.9671882 , 0.14600426,
        0.56323606, 0.63439196, 0.49546736]], dtype=float32)

In [7]:
# 단일 텐서에서 값으로 반환하기
x = torch.ones(1)  
x.item()    #.item()은 손실 함숫값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어 준다.

1.0